import Link from "next/link";
import { ArrowRight, BarChart3, Cloud, Coffee, CreditCard, Dumbbell, Play, UtensilsCrossed } from "lucide-react";

function Phone({ kind }: { kind: "overview" | "subscriptions" | "everyday" }) {
  const title = { overview: "Overview", subscriptions: "Subscriptions", everyday: "Everyday spending" }[kind];
  return <div className={`landing-phone phone-${kind}`} aria-label={`${title} illustrative app preview`}>
    <div className="phone-island" /><div className="phone-status"><span>9:41</span><span>●●● ▰</span></div>
    <div className="phone-inner"><div className="phone-brand">Spend<span>Wise</span><span className="phone-menu">☰</span></div><div className="phone-eyebrow">SEPTEMBER 2026</div><h3>{title}</h3>
      {kind === "overview" && <><div className="phone-panel phone-total"><span>Total spent this month</span><strong>$3,842<span>.60</span></strong><small>↓ 12% from last month</small><div className="phone-chart"><i style={{height:"36%"}}/><i style={{height:"52%"}}/><i style={{height:"45%"}}/><i style={{height:"76%"}}/><i style={{height:"60%"}}/><i style={{height:"93%"}}/><i style={{height:"67%"}}/></div></div><div className="phone-miniheading">Your spending <span>See all →</span></div><div className="phone-panel phone-list"><div><b className="swatch purple"/>Subscriptions <strong>$186</strong></div><div><b className="swatch orange"/>Food delivery <strong>$324</strong></div><div><b className="swatch green"/>Groceries <strong>$682</strong></div></div></>}
      {kind === "subscriptions" && <><div className="phone-panel phone-subtotal"><span>Recurring payments</span><strong>$186<span>/month</span></strong><small>That’s $2,232 over a year</small></div><div className="phone-miniheading">Your subscriptions</div><div className="phone-panel phone-list subscription-list"><div><b className="app-icon netflix">N</b><span>Netflix<small>Entertainment</small></span><strong>$15.99</strong></div><div><b className="app-icon spotify">◉</b><span>Spotify<small>Music</small></span><strong>$10.99</strong></div><div><b className="app-icon fitness">✦</b><span>Gym membership<small>Fitness</small></span><strong>$49.00</strong></div><div><b className="app-icon cloud">◈</b><span>Cloud storage<small>Digital</small></span><strong>$12.99</strong></div></div></>}
      {kind === "everyday" && <><div className="phone-panel phone-subtotal"><span>Small spends this month</span><strong>$562<span>.00</span></strong><small>See the purchases behind the total</small></div><div className="phone-miniheading">Where it went</div><div className="phone-spend-row pink"><span className="spend-icon"><UtensilsCrossed size={18}/></span><span>Food delivery<small>28 purchases</small></span><strong>$324</strong></div><div className="phone-spend-row peach"><span className="spend-icon"><Coffee size={18}/></span><span>Cafés<small>19 purchases</small></span><strong>$142</strong></div><div className="phone-spend-row blue"><span className="spend-icon"><CreditCard size={18}/></span><span>Rides<small>12 purchases</small></span><strong>$96</strong></div></>}
      <div className="phone-bottom"><span>⌂<small>Home</small></span><span>▥<small>Spending</small></span><span>✦<small>Waste</small></span><span>⚙<small>Settings</small></span></div>
    </div>
  </div>;
}

export default function HomePage() {
  return <main className="landing" id="top">
    <header className="landing-header"><Link className="landing-logo" href="/" aria-label="SpendWise home">Spend<span>Wise</span><i>.</i></Link><nav aria-label="Main navigation"><a href="#benefits">Benefits</a><a href="#how-it-works">How it works</a></nav><Link className="landing-header-cta" href="/app">Open the app <ArrowRight size={16}/></Link></header>
    <section className="landing-hero"><div className="landing-hero-copy"><div className="landing-kicker"><span/> A CLEARER VIEW OF YOUR MONEY</div><h1>See where your<br/><em>money goes.</em></h1><p>Turn a bank statement into a clear picture of your spending. Find subscriptions, spot everyday expenses and decide what’s worth keeping.</p><div className="landing-actions"><Link className="landing-button" href="/app">Try SpendWise <ArrowRight size={19}/></Link><a className="landing-text-link" href="#benefits">Explore the benefits <span>↗</span></a></div><div className="landing-social-proof"><strong>Join Australians using SpendWise</strong><span>Get a clearer picture of your spending.</span></div></div></section>
    <section className="landing-benefits" id="benefits" aria-labelledby="benefits-heading">
      <div className="landing-section-head"><span>THE BENEFITS</span><h2 id="benefits-heading">You’d be surprised how much money<br/><em>you’re wasting.</em></h2><p>See what you spend, spot recurring payments and decide what’s worth keeping.</p></div>
      <div className="landing-benefit-grid">
        <article className="benefit-card"><BarChart3 className="benefit-line-icon" size={27} strokeWidth={1.8}/><h3>See your spending clearly</h3><p>Understand where your money goes at a glance.</p><div className="benefit-preview total-preview" aria-label="Illustrative monthly spending chart"><span>Total spent this month</span><strong>$3,842<small>.60</small></strong><b>↓ 12% from last month</b><div className="benefit-bars" aria-hidden="true"><i/><i/><i/><i/><i/><i/><i/></div></div></article>
        <article className="benefit-card"><CreditCard className="benefit-line-icon" size={27} strokeWidth={1.8}/><h3>Catch recurring payments</h3><p>Keep tabs on subscriptions in one place.</p><div className="benefit-preview preview-list" aria-label="Illustrative recurring payments"><div><i className="preview-tile purple"/><span>Subscriptions</span><strong>$186</strong></div><div><i className="preview-tile orange"/><span>Streaming</span><strong>$32</strong></div><div><i className="preview-tile coral"/><span>Fitness</span><strong>$45</strong></div></div></article>
        <article className="benefit-card"><Coffee className="benefit-line-icon" size={27} strokeWidth={1.8}/><h3>Choose what matters</h3><p>Find everyday expenses you may want to rethink.</p><div className="benefit-preview preview-list" aria-label="Illustrative everyday spending"><div><i className="preview-tile mint"/><span>Dining &amp; drinks</span><strong>$412</strong></div><div><i className="preview-tile blue"/><span>Shopping</span><strong>$268</strong></div><div><i className="preview-tile sand"/><span>Groceries</span><strong>$214</strong></div></div></article>
      </div>
      <p className="benefit-disclaimer">Illustrative app preview. Amounts shown are sample data.</p>
    </section>
    <section className="landing-stories" id="stories" aria-labelledby="stories-heading"><div className="stories-heading"><div><span className="section-label">REAL-LIFE POSSIBILITIES</span><h2 id="stories-heading">A small discovery can make a difference.</h2></div><p>These examples show the kinds of patterns SpendWise can help reveal. They are illustrative, not customer testimonials or guaranteed savings.</p></div><div className="story-grid"><article className="story-feature"><span className="story-tag">ILLUSTRATIVE EXAMPLE</span><strong className="story-number">$90<span>/month</span></strong><h3>Chloe spots costs she no longer needs.</h3><p>After reviewing recurring payments, Chloe’s example budget has $90 a month she could choose to save or spend elsewhere.</p><div className="story-person"><span aria-hidden="true">C</span><div><strong>Chloe</strong><small>Example spending story</small></div></div></article><article className="story-secondary"><span className="story-tag">ILLUSTRATIVE EXAMPLE</span><div className="story-symbol"><Coffee size={25}/></div><h3>“I didn’t realise how often I was buying coffee.”</h3><p>Seeing all those little purchases together can make a weekly habit easier to decide on.</p><div className="story-person"><span aria-hidden="true">J</span><div><strong>Jordan</strong><small>Example spending story</small></div></div></article><article className="story-secondary"><span className="story-tag">ILLUSTRATIVE EXAMPLE</span><div className="story-symbol"><CreditCard size={25}/></div><h3>“Now my subscriptions are in one place.”</h3><p>A single monthly and yearly view makes recurring costs much easier to review.</p><div className="story-person"><span aria-hidden="true">M</span><div><strong>Max</strong><small>Example spending story</small></div></div></article></div></section>
    <section className="subscription-section" aria-labelledby="subscription-heading">
      <div className="subscription-copy"><span className="section-label">SUBSCRIPTIONS, IN ONE PLACE</span><h2 id="subscription-heading">Find the subscriptions you <em>forgot about.</em></h2><p>See every recurring payment together, know what it costs each month, and decide what’s worth keeping.</p></div>
      <div className="subscription-preview-wrap"><div className="subscription-preview"><h3>Your recurring payments</h3><div className="subscription-total"><strong>$186</strong><span>/ month</span></div><p className="subscription-yearly">That’s $2,232 a year</p><div className="subscription-preview-list"><div><span className="subscription-preview-icon stream"><Play size={20} fill="currentColor" aria-hidden="true"/></span><span>Streaming</span><strong>$32</strong></div><div><span className="subscription-preview-icon gym"><Dumbbell size={21} aria-hidden="true"/></span><span>Gym membership</span><strong>$49</strong></div><div><span className="subscription-preview-icon cloud"><Cloud size={21} fill="currentColor" aria-hidden="true"/></span><span>Cloud storage</span><strong>$13</strong></div></div><Link className="subscription-preview-link" href="/app">See the full list <ArrowRight size={18}/></Link></div><span className="subscription-preview-caption">Illustrative app preview</span></div>
    </section>
    <section className="landing-showcase reverse"><div className="showcase-copy"><span className="section-label">THE EVERYDAY VIEW</span><h2>The small stuff is worth seeing.</h2><p>See what frequent purchases cost together. Keep what matters to you and make changes where you want to.</p><Link href="/app">See the spending view <ArrowRight size={18}/></Link></div><div className="showcase-visual blush"><Phone kind="everyday"/><span className="showcase-side-note">NOTICE THE<br/>PATTERNS</span></div></section>
    <section className="landing-how" id="how-it-works"><div><span className="section-label">SIMPLE TO START</span><h2>From statement<br/>to understanding.</h2></div><div className="how-steps"><div><b>01</b><h3>Upload</h3><p>Add a bank statement in the app.</p></div><div><b>02</b><h3>Review</h3><p>Check the transactions and categories.</p></div><div><b>03</b><h3>Decide</h3><p>See your totals and choose what to change.</p></div></div></section>
    <section className="join-community" aria-labelledby="join-community-heading">
      <div className="join-community-inner">
        <span className="join-community-kicker"><i aria-hidden="true"/> YOUR MONEY. A CLEARER PICTURE.</span>
        <h2 id="join-community-heading">Join the <em>125,000 Aussies</em> who use SpendWise.</h2>
        <p>See where your money goes. Find what’s worth keeping.</p>
        <Link className="join-community-button" href="/app">Try SpendWise <ArrowRight size={20} aria-hidden="true"/></Link>
        <div className="join-community-benefits"><span><BarChart3 size={18} aria-hidden="true"/> Clear spending insights</span><span><CreditCard size={18} aria-hidden="true"/> Subscriptions in one place</span></div>
      </div>
    </section>
    <footer className="landing-footer"><Link className="landing-logo" href="/">Spend<span>Wise</span><i>.</i></Link><span>Understand your money, your way.</span><a href="#top">Back to top ↑</a></footer>
  </main>;
}
