import Link from "next/link";
import { ArrowRight, BarChart3, Cloud, Coffee, CreditCard, Dumbbell, Play } from "lucide-react";

export default function HomePage() {
  return <main className="landing" id="top">
    <header className="landing-header"><Link className="landing-logo" href="/" aria-label="SpendWise home">Spend<span>Wise</span><i>.</i></Link><nav aria-label="Main navigation"><a href="#benefits">Benefits</a><a href="#how-it-works">How it works</a></nav><Link className="landing-header-cta" href="/app">Open the app <ArrowRight size={16}/></Link></header>
    <section className="landing-hero"><div className="landing-hero-copy"><div className="landing-kicker"><span/> A CLEARER VIEW OF YOUR MONEY</div><h1>See where your<br/><em>money goes.</em></h1><p>Turn a bank statement into a clear picture of your spending. Find subscriptions, spot everyday expenses and decide what’s worth keeping.</p><div className="landing-actions"><Link className="landing-button" href="/app">Try SpendWise <ArrowRight size={19}/></Link><a className="landing-text-link" href="#benefits">Explore the benefits <span>↗</span></a></div><div className="landing-social-proof"><strong>Join Australians using SpendWise</strong><span>Get a clearer picture of your spending.</span></div></div></section>
    <section className="landing-benefits" id="benefits" aria-labelledby="benefits-heading">
      <div className="landing-section-head"><span>THE BENEFITS</span><h2 id="benefits-heading">You’d be surprised how much money<br/><em>you’re wasting.</em></h2><p>See what you spend, spot recurring payments and decide what’s worth keeping.</p></div>
      <div className="landing-benefit-grid">
        <article className="benefit-card"><BarChart3 className="benefit-line-icon" size={27} strokeWidth={1.8}/><h3>See your spending clearly</h3><p>Understand where your money goes at a glance.</p><div className="benefit-preview total-preview" aria-label="Illustrative monthly spending chart"><span>Total spent this month</span><strong>$3,842<small>.60</small></strong><b>↓ 12% from last month</b><div className="benefit-bars" aria-hidden="true"><i/><i/><i/><i/><i/><i/><i/></div></div></article>
        <article className="benefit-card"><CreditCard className="benefit-line-icon" size={27} strokeWidth={1.8}/><h3>Catch recurring payments</h3><p>Keep tabs on subscriptions in one place.</p><div className="benefit-preview preview-list" aria-label="Illustrative recurring payments"><div><i className="preview-tile purple"/><span>Subscriptions</span><strong>$186</strong></div><div><i className="preview-tile orange"/><span>Streaming</span><strong>$32</strong></div><div><i className="preview-tile coral"/><span>Fitness</span><strong>$45</strong></div></div></article>
        <article className="benefit-card"><Coffee className="benefit-line-icon" size={27} strokeWidth={1.8}/><h3>Choose what matters</h3><p>Find everyday expenses you may want to rethink.</p><div className="benefit-preview preview-list" aria-label="Illustrative everyday spending"><div><i className="preview-tile mint"/><span>Dining &amp; drinks</span><strong>$412</strong></div><div><i className="preview-tile blue"/><span>Shopping</span><strong>$268</strong></div><div><i className="preview-tile sand"/><span>Groceries</span><strong>$214</strong></div></div></article>
      </div>
      <p className="benefit-disclaimer">Illustrative app preview. Amounts shown are sample data.</p>
    </section>
    <section className="landing-stories" id="stories" aria-labelledby="stories-heading"><div className="stories-heading"><div><span className="section-label">REAL-LIFE POSSIBILITIES</span><h2 id="stories-heading">A small discovery can make a difference.</h2></div><p>These examples show the kinds of patterns SpendWise can help reveal. They are illustrative, not customer testimonials or guaranteed savings.</p></div><div className="story-grid"><article className="story-feature"><span className="story-tag">ILLUSTRATIVE EXAMPLE</span><strong className="story-number">$90<span>/month</span></strong><h3>Chloe spots costs she no longer needs.</h3><p>After reviewing recurring payments, Chloe’s example budget has $90 a month she could choose to save or spend elsewhere.</p><div className="story-person"><span aria-hidden="true">C</span><div><strong>Chloe</strong><small>Example spending story</small></div></div></article><article className="story-secondary"><span className="story-tag">ILLUSTRATIVE EXAMPLE</span><div className="story-symbol"><Coffee size={25}/></div><h3>“I didn’t realise how often I was buying coffee.”</h3><p>Seeing all those little purchases together can make a weekly habit easier to decide on.</p><div className="story-person"><span aria-hidden="true">J</span><div><strong>Jordan</strong><small>Example spending story</small></div></div></article><article className="story-secondary"><span className="story-tag">ILLUSTRATIVE EXAMPLE</span><div className="story-symbol"><CreditCard size={25}/></div><h3>“Now my subscriptions are in one place.”</h3><p>A single monthly and yearly view makes recurring costs much easier to review.</p><div className="story-person"><span aria-hidden="true">M</span><div><strong>Max</strong><small>Example spending story</small></div></div></article></div></section>
    <section className="subscription-section" aria-labelledby="subscription-heading">
      <div className="subscription-copy"><span className="section-label">SUBSCRIPTIONS, IN ONE PLACE</span><h2 id="subscription-heading">Find the subscriptions you <em>forgot about.</em></h2><p>See every recurring payment together, know what it costs each month, and decide what’s worth keeping.</p></div>
      <div className="subscription-preview-wrap"><div className="subscription-preview"><h3>Your recurring payments</h3><div className="subscription-total"><strong>$186</strong><span>/ month</span></div><p className="subscription-yearly">That’s $2,232 a year</p><div className="subscription-preview-list"><div><span className="subscription-preview-icon stream"><Play size={20} fill="currentColor" aria-hidden="true"/></span><span>Streaming</span><strong>$32</strong></div><div><span className="subscription-preview-icon gym"><Dumbbell size={21} aria-hidden="true"/></span><span>Gym membership</span><strong>$49</strong></div><div><span className="subscription-preview-icon cloud"><Cloud size={21} fill="currentColor" aria-hidden="true"/></span><span>Cloud storage</span><strong>$13</strong></div></div><Link className="subscription-preview-link" href="/app">See the full list <ArrowRight size={18}/></Link></div><span className="subscription-preview-caption">Illustrative app preview</span></div>
    </section>
    <section className="join-community" aria-labelledby="join-community-heading">
      <div className="join-community-inner">
        <span className="join-community-kicker"><i aria-hidden="true"/> A CLEARER VIEW OF YOUR MONEY</span>
        <h2 id="join-community-heading"><span>Join the</span> <em>125k Aussies</em> <span>who use SpendWise.</span></h2>
        <p>See where your money goes, spot recurring payments and decide what’s worth keeping.</p>
        <Link className="join-community-button" href="/app">Try SpendWise <ArrowRight size={22} aria-hidden="true"/></Link>
      </div>
    </section>
    <section className="landing-how" id="how-it-works"><div><span className="section-label">SIMPLE TO START</span><h2>From statement<br/>to understanding.</h2></div><div className="how-steps"><div><b>01</b><h3>Upload</h3><p>Add a bank statement in the app.</p></div><div><b>02</b><h3>Review</h3><p>Check the transactions and categories.</p></div><div><b>03</b><h3>Decide</h3><p>See your totals and choose what to change.</p></div></div></section>
    <footer className="landing-footer"><Link className="landing-logo" href="/">Spend<span>Wise</span><i>.</i></Link><span>Understand your money, your way.</span><a href="#top">Back to top ↑</a></footer>
  </main>;
}
